export type ReadingLesson = {
  id:string; level:"N5"|"N4"; kind:string; title:string; canDo:string;
  text:string; reading:string; meaning:string; vocabulary:{word:string;reading:string;meaning:string}[];
  question:string; choices:string[]; answer:string; explanation:string;
};

export const READING_LESSONS: ReadingLesson[] = [
  {id:"message",level:"N5",kind:"Pesan",title:"Pesan dari teman",canDo:"Memahami waktu dan tempat pertemuan",text:"リナさんへ\nあした、駅の前で会いましょう。時間は午後三時です。雨のときは、駅の中のカフェにいます。\n田中",reading:"Rina-san e. Ashita, eki no mae de aimashou. Jikan wa gogo sanji desu. Ame no toki wa, eki no naka no kafe ni imasu. Tanaka.",meaning:"Untuk Rina. Besok mari bertemu di depan stasiun. Waktunya pukul tiga sore. Jika hujan, saya berada di kafe dalam stasiun. Tanaka.",vocabulary:[{word:"駅の前",reading:"えきのまえ",meaning:"depan stasiun"},{word:"雨のとき",reading:"あめのとき",meaning:"ketika hujan"}],question:"Jika hujan, Tanaka menunggu di mana?",choices:["Depan stasiun","Dalam kafe di stasiun","Rumah Rina","Halte bus"],answer:"Dalam kafe di stasiun",explanation:"Kalimat 雨のときは、駅の中のカフェにいます menyebut lokasi saat hujan."},
  {id:"shop-sign",level:"N5",kind:"Papan toko",title:"Jam buka toko",canDo:"Mengambil informasi dari papan pengumuman",text:"パン屋「さくら」\n月曜日〜土曜日　午前八時〜午後六時\n日曜日は休みです。\n午後五時からパンが二十パーセント安くなります。",reading:"Pan-ya Sakura. Getsuyoubi kara doyoubi, gozen hachiji kara gogo rokuji. Nichiyoubi wa yasumi desu. Gogo goji kara pan ga nijuppaasento yasuku narimasu.",meaning:"Toko roti Sakura. Senin–Sabtu, pukul 08.00–18.00. Minggu tutup. Mulai pukul 17.00 roti menjadi 20% lebih murah.",vocabulary:[{word:"休み",reading:"やすみ",meaning:"libur"},{word:"安くなる",reading:"やすくなる",meaning:"menjadi lebih murah"}],question:"Kapan roti mulai mendapat potongan harga?",choices:["08.00","17.00","18.00","Minggu"],answer:"17.00",explanation:"午後五時から berarti mulai pukul lima sore."},
  {id:"daily",level:"N5",kind:"Cerita pendek",title:"Hari Minggu Yuki",canDo:"Memahami urutan kegiatan sederhana",text:"日曜日、ゆきさんは九時に起きました。朝ご飯を食べてから、部屋を掃除しました。午後は友達と公園へ行きました。晩ご飯の前に、一時間日本語を勉強しました。",reading:"Nichiyoubi, Yuki-san wa kuji ni okimashita. Asagohan o tabete kara, heya o souji shimashita. Gogo wa tomodachi to kouen e ikimashita. Bangohan no mae ni, ichijikan nihongo o benkyou shimashita.",meaning:"Hari Minggu Yuki bangun pukul sembilan. Setelah sarapan, ia membersihkan kamar. Sore hari ia pergi ke taman bersama teman. Sebelum makan malam, ia belajar bahasa Jepang satu jam.",vocabulary:[{word:"掃除する",reading:"そうじする",meaning:"membersihkan"},{word:"〜てから",reading:"〜てから",meaning:"setelah melakukan"}],question:"Apa yang dilakukan Yuki setelah sarapan?",choices:["Belajar Jepang","Pergi ke taman","Membersihkan kamar","Makan malam"],answer:"Membersihkan kamar",explanation:"朝ご飯を食べてから、部屋を掃除しました menunjukkan tindakan setelah sarapan."},
  {id:"train",level:"N5",kind:"Informasi",title:"Jadwal kereta",canDo:"Mencari informasi keberangkatan",text:"東京行き\n普通　10:05　3番線\n急行　10:20　2番線\n普通　10:35　3番線\n※急行は新宿まで止まりません。",reading:"Toukyou-yuki. Futsuu juuji gofun sanbansen. Kyuukou juuji nijuppun nibansen. Kyuukou wa Shinjuku made tomarimasen.",meaning:"Tujuan Tokyo. Lokal 10.05 jalur 3. Ekspres 10.20 jalur 2. Lokal 10.35 jalur 3. Kereta ekspres tidak berhenti sampai Shinjuku.",vocabulary:[{word:"普通",reading:"ふつう",meaning:"kereta lokal"},{word:"急行",reading:"きゅうこう",meaning:"kereta ekspres"}],question:"Kereta pukul 10.20 berangkat dari jalur berapa?",choices:["1","2","3","Tidak tertulis"],answer:"2",explanation:"Baris 急行 10:20 2番線 menunjukkan jalur 2."},
  {id:"invitation",level:"N4",kind:"Email",title:"Undangan pesta",canDo:"Memahami rencana dan permintaan dalam email",text:"みなさんへ\n来週の土曜日に、アリさんの送別会をします。場所は駅の近くの「海」というレストランです。午後六時までに来てください。参加できない人は、木曜日までに山田さんに連絡してください。",reading:"Minasan e. Raishuu no doyoubi ni, Ari-san no soubetsukai o shimasu. Basho wa eki no chikaku no Umi to iu resutoran desu. Gogo rokuji made ni kite kudasai. Sanka dekinai hito wa, mokuyoubi made ni Yamada-san ni renraku shite kudasai.",meaning:"Untuk semuanya. Sabtu depan akan diadakan pesta perpisahan Ari. Tempatnya restoran bernama Umi dekat stasiun. Harap datang paling lambat pukul enam sore. Yang tidak dapat hadir, harap menghubungi Yamada paling lambat Kamis.",vocabulary:[{word:"送別会",reading:"そうべつかい",meaning:"pesta perpisahan"},{word:"参加する",reading:"さんかする",meaning:"berpartisipasi"}],question:"Apa yang harus dilakukan orang yang tidak bisa hadir?",choices:["Datang sebelum pukul enam","Menghubungi Ari hari Sabtu","Menghubungi Yamada sebelum Kamis berakhir","Pergi ke stasiun"],answer:"Menghubungi Yamada sebelum Kamis berakhir",explanation:"参加できない人は、木曜日までに山田さんに連絡してください adalah instruksi untuk yang tidak hadir."},
  {id:"weather",level:"N4",kind:"Pengumuman",title:"Perubahan acara karena cuaca",canDo:"Memahami sebab dan perubahan rencana",text:"明日のスポーツ大会について\n天気予報によると、明日は朝から強い雨が降るそうです。そのため、大会は日曜日に延期します。時間と場所は変わりません。参加する人は、運動靴と飲み物を持ってきてください。",reading:"Ashita no supootsu taikai ni tsuite. Tenki yohou ni yoru to, ashita wa asa kara tsuyoi ame ga furu sou desu. Sono tame, taikai wa nichiyoubi ni enki shimasu. Jikan to basho wa kawarimasen.",meaning:"Tentang pertandingan olahraga besok. Menurut ramalan cuaca, katanya hujan deras turun sejak pagi. Oleh karena itu, acara ditunda sampai Minggu. Waktu dan tempat tidak berubah. Peserta harap membawa sepatu olahraga dan minuman.",vocabulary:[{word:"延期する",reading:"えんきする",meaning:"menunda"},{word:"そのため",reading:"そのため",meaning:"oleh karena itu"}],question:"Apa yang berubah dari rencana acara?",choices:["Hari pelaksanaan","Tempat","Waktu mulai","Barang bawaan"],answer:"Hari pelaksanaan",explanation:"大会は日曜日に延期します menyebut acara dipindah ke hari Minggu; waktu dan tempat tetap."},
  {id:"apartment",level:"N4",kind:"Iklan",title:"Mencari apartemen",canDo:"Membandingkan syarat dan fasilitas",text:"さくらアパート\n駅から歩いて八分。部屋は二つ、台所とお風呂があります。家賃は一か月六万円です。インターネットは無料ですが、ペットを飼うことはできません。近くにスーパーと病院があります。",reading:"Sakura apaato. Eki kara aruite happun. Heya wa futatsu, daidokoro to ofuro ga arimasu. Yachin wa ikkagetsu rokuman-en desu. Intaanetto wa muryou desu ga, petto o kau koto wa dekimasen.",meaning:"Apartemen Sakura. Delapan menit berjalan kaki dari stasiun. Ada dua kamar, dapur, dan kamar mandi. Sewa 60.000 yen per bulan. Internet gratis, tetapi tidak boleh memelihara hewan. Dekat supermarket dan rumah sakit.",vocabulary:[{word:"家賃",reading:"やちん",meaning:"uang sewa"},{word:"無料",reading:"むりょう",meaning:"gratis"}],question:"Pernyataan mana yang benar?",choices:["Boleh memelihara kucing","Internet harus dibayar terpisah","Ada supermarket di dekatnya","Jauh dari stasiun"],answer:"Ada supermarket di dekatnya",explanation:"近くにスーパーと病院があります berarti supermarket dan rumah sakit berada di dekatnya."},
  {id:"clinic",level:"N4",kind:"Percakapan",title:"Di klinik",canDo:"Memahami gejala dan saran dokter",text:"医者：どうしましたか。\n患者：昨日から頭が痛くて、少し熱もあります。\n医者：風邪でしょう。今日は薬を飲んで、ゆっくり休んでください。熱が下がらなかったら、金曜日にもう一度来てください。",reading:"Isha: Dou shimashita ka. Kanja: Kinou kara atama ga itakute, sukoshi netsu mo arimasu. Isha: Kaze deshou. Kyou wa kusuri o nonde, yukkuri yasunde kudasai. Netsu ga sagaranakattara, kinyoubi ni mou ichido kite kudasai.",meaning:"Dokter: Ada keluhan apa? Pasien: Sejak kemarin kepala sakit dan sedikit demam. Dokter: Mungkin pilek. Hari ini minum obat dan istirahatlah. Jika demam tidak turun, datang lagi hari Jumat.",vocabulary:[{word:"熱が下がる",reading:"ねつがさがる",meaning:"demam turun"},{word:"患者",reading:"かんじゃ",meaning:"pasien"}],question:"Kapan pasien harus kembali?",choices:["Pasti besok","Jika demam tidak turun","Setelah obat habis","Setiap Jumat"],answer:"Jika demam tidak turun",explanation:"熱が下がらなかったら adalah syarat: apabila demam tidak turun."},
  {id:"lost",level:"N4",kind:"Pengumuman",title:"Barang tertinggal",canDo:"Menemukan informasi penting dalam pengumuman",text:"忘れ物のお知らせ\n本日、図書館の二階で黒い財布が見つかりました。中に学生証と電車のカードが入っています。心当たりがある人は、図書館一階の受付まで来てください。受付は午後八時に閉まります。",reading:"Wasuremono no oshirase. Honjitsu, toshokan no nikai de kuroi saifu ga mitsukarimashita. Naka ni gakuseishou to densha no kaado ga haitte imasu. Kokoroatari ga aru hito wa, toshokan ikkai no uketsuke made kite kudasai.",meaning:"Pemberitahuan barang tertinggal. Hari ini ditemukan dompet hitam di lantai dua perpustakaan. Di dalamnya ada kartu pelajar dan kartu kereta. Yang merasa memilikinya harap datang ke resepsionis lantai satu. Resepsionis tutup pukul delapan malam.",vocabulary:[{word:"忘れ物",reading:"わすれもの",meaning:"barang tertinggal"},{word:"受付",reading:"うけつけ",meaning:"resepsionis"}],question:"Di mana pemilik mengambil dompetnya?",choices:["Lantai dua","Stasiun","Resepsionis lantai satu","Kantor sekolah"],answer:"Resepsionis lantai satu",explanation:"図書館一階の受付まで来てください menunjukkan tempat pengambilan."},
  {id:"trip",level:"N4",kind:"Blog",title:"Perjalanan singkat ke Kyoto",canDo:"Memahami pengalaman dan pendapat",text:"先月、家族と京都へ行きました。京都は二回目でしたが、秋に行ったのは初めてです。紅葉がとてもきれいで、写真をたくさん撮りました。有名なお寺は人が多すぎたので、朝早く行ったほうがいいと思います。次は春の京都も見てみたいです。",reading:"Sengetsu, kazoku to Kyouto e ikimashita. Kyouto wa nikaime deshita ga, aki ni itta no wa hajimete desu. Kouyou ga totemo kirei de, shashin o takusan torimashita. Yuumei na otera wa hito ga oosugita node, asa hayaku itta hou ga ii to omoimasu.",meaning:"Bulan lalu saya pergi ke Kyoto bersama keluarga. Itu kedua kalinya ke Kyoto, tetapi pertama kali pada musim gugur. Daun musim gugur sangat indah dan saya mengambil banyak foto. Kuil terkenal terlalu ramai, jadi menurut saya sebaiknya datang pagi-pagi. Berikutnya saya juga ingin mencoba melihat Kyoto pada musim semi.",vocabulary:[{word:"紅葉",reading:"こうよう",meaning:"daun musim gugur"},{word:"二回目",reading:"にかいめ",meaning:"kali kedua"}],question:"Saran penulis untuk mengunjungi kuil terkenal adalah…",choices:["Datang saat musim panas","Datang pagi-pagi","Jangan mengambil foto","Pergi sendirian"],answer:"Datang pagi-pagi",explanation:"朝早く行ったほうがいいと思います adalah saran datang lebih awal."},
];

export type Drill = {id:string;level:"N5"|"N4";skill:"Kosakata"|"Bunpou"|"Susun kalimat"|"Membaca"|"Listening";prompt:string;context?:string;choices:string[];answer:string;explanation:string;audio?:string};
export const JLPT_DRILLS: Drill[] = [
  {id:"v1",level:"N5",skill:"Kosakata",prompt:"「あさ」の漢字はどれですか。",choices:["朝","昼","夜","先"],answer:"朝",explanation:"朝（あさ） berarti pagi."},
  {id:"v2",level:"N5",skill:"Kosakata",prompt:"毎日、図書館で本を（　）。",choices:["読みます","聞きます","飲みます","会います"],answer:"読みます",explanation:"本を読む berarti membaca buku."},
  {id:"v3",level:"N4",skill:"Kosakata",prompt:"「準備」と意味が近いものはどれですか。",choices:["用意","反対","経験","説明"],answer:"用意",explanation:"準備 dan 用意 sama-sama berarti persiapan."},
  {id:"v4",level:"N4",skill:"Kosakata",prompt:"電車が遅れたので、会社に（　）しました。",choices:["連絡","遠慮","運転","見物"],answer:"連絡",explanation:"連絡する berarti menghubungi/memberi kabar."},
  {id:"g1",level:"N5",skill:"Bunpou",prompt:"私は毎朝七時（　）起きます。",choices:["に","で","を","へ"],answer:"に",explanation:"Waktu tertentu ditandai に."},
  {id:"g2",level:"N5",skill:"Bunpou",prompt:"この部屋（　）猫がいます。",choices:["に","で","を","と"],answer:"に",explanation:"Tempat keberadaan memakai に; yang ada ditandai が."},
  {id:"g3",level:"N5",skill:"Bunpou",prompt:"ここで写真を撮っ（　）いいですか。",choices:["ても","ては","たり","たら"],answer:"ても",explanation:"〜てもいいですか dipakai untuk meminta izin."},
  {id:"g4",level:"N4",skill:"Bunpou",prompt:"日本へ行ったこと（　）あります。",choices:["が","を","に","で"],answer:"が",explanation:"Pola pengalaman adalah Vたことがあります."},
  {id:"g5",level:"N4",skill:"Bunpou",prompt:"雨が降っ（　）、試合はあります。",choices:["ても","ながら","ばかり","そう"],answer:"ても",explanation:"〜ても berarti meskipun kondisi terjadi."},
  {id:"g6",level:"N4",skill:"Bunpou",prompt:"駅に着い（　）、電話してください。",choices:["たら","そう","ので","ながら"],answer:"たら",explanation:"〜たら dapat berarti kalau/setelah kondisi terpenuhi."},
  {id:"s1",level:"N5",skill:"Susun kalimat",prompt:"Susun kalimat yang benar.",context:"[①です　②田中　③は　④私]",choices:["④③②①","④②③①","②④③①","③④②①"],answer:"④③②①",explanation:"私は田中です。 Topik 私 diikuti は, lalu informasi 田中です."},
  {id:"s2",level:"N4",skill:"Susun kalimat",prompt:"Susun kalimat yang benar.",context:"[①前に　②寝る　③本を　④読みます]",choices:["②①③④","①②③④","③①②④","②③①④"],answer:"②①③④",explanation:"寝る前に本を読みます。 Sebelum tidur, saya membaca buku."},
  {id:"t1",level:"N5",skill:"Membaca",prompt:"この店は日曜日は休みです。今日は日曜日です。",choices:["Toko buka","Toko tutup","Toko murah","Tidak diketahui"],answer:"Toko tutup",explanation:"日曜日は休み berarti hari Minggu libur."},
  {id:"t2",level:"N4",skill:"Membaca",prompt:"会議は三時の予定でしたが、四時に変わりました。",choices:["Rapat dibatalkan","Rapat dimajukan","Rapat diundur satu jam","Rapat tetap pukul tiga"],answer:"Rapat diundur satu jam",explanation:"Jadwal berubah dari pukul tiga menjadi empat."},
  {id:"l1",level:"N5",skill:"Listening",prompt:"Dengarkan lalu pilih jawaban yang tepat.",audio:"あした、九時に駅で会いましょう。",choices:["Hari ini pukul 9","Besok pukul 9 di stasiun","Besok pukul 8 di sekolah","Minggu di stasiun"],answer:"Besok pukul 9 di stasiun",explanation:"あした = besok, 九時 = pukul sembilan, 駅で = di stasiun."},
  {id:"l2",level:"N4",skill:"Listening",prompt:"Dengarkan alasan pembicara.",audio:"電車が遅れたので、約束の時間に間に合いませんでした。",choices:["Bangun terlambat","Kereta terlambat","Lupa janji","Salah stasiun"],answer:"Kereta terlambat",explanation:"電車が遅れたので menyatakan sebabnya kereta terlambat."},
];

export const SPEAKING_PROMPTS = [
  {id:"intro",level:"N5",title:"Perkenalan 20 detik",model:"はじめまして。アリです。インドネシアから来ました。日本語を勉強しています。どうぞよろしくお願いします。",task:"Ganti nama, asal, dan kegiatan dengan informasi tentang dirimu.",checks:["Nama terdengar jelas","Gunakan 〜から来ました","Akhiri dengan よろしくお願いします"]},
  {id:"routine",level:"N5",title:"Rutinitas pagi",model:"毎朝六時に起きます。七時に朝ご飯を食べて、八時に学校へ行きます。",task:"Ceritakan tiga kegiatan pagimu dengan waktu.",checks:["Gunakan に untuk waktu","Urutkan dengan bentuk て","Ucapkan angka dengan jelas"]},
  {id:"order",level:"N5",title:"Pesan makanan",model:"すみません。ラーメンを一つと、水をお願いします。",task:"Pesan satu makanan dan satu minuman.",checks:["Awali dengan すみません","Pakai を dan と","Akhiri dengan お願いします"]},
  {id:"experience",level:"N4",title:"Pengalaman",model:"京都へ行ったことがあります。お寺を見たり、日本料理を食べたりしました。",task:"Ceritakan tempat yang pernah kamu kunjungi dan dua kegiatan di sana.",checks:["Gunakan 〜たことがあります","Berikan dua contoh dengan 〜たり","Jangan membaca romaji"]},
  {id:"plan",level:"N4",title:"Rencana akhir pekan",model:"週末は友達と映画を見るつもりです。時間があったら、レストランにも行きたいです。",task:"Jelaskan rencana dan satu hal yang ingin dilakukan jika ada waktu.",checks:["Gunakan つもりです","Gunakan 〜たら","Gunakan 〜たいです"]},
  {id:"opinion",level:"N4",title:"Pendapat sederhana",model:"日本語は難しいですが、面白いと思います。毎日少しずつ勉強したほうがいいです。",task:"Sampaikan pendapat dan satu saran tentang belajar bahasa Jepang.",checks:["Gunakan と思います","Hubungkan dengan が","Berikan saran 〜たほうがいい"]},
];

