export type ParticleGuide = { picture:string; choose:string; mistake:string; memory:string };

export const PARTICLE_GUIDES: Record<string,ParticleGuide> = {
  wa:{picture:"Bayangkan は sebagai papan judul: ‘kalau soal A…’. Ia menetapkan topik, bukan selalu pelaku tindakan.",choose:"Pakai ketika A sudah ada dalam konteks, ketika membuka topik, atau saat membandingkan A dengan hal lain.",mistake:"Jangan otomatis menerjemahkan は sebagai ‘adalah’. Pada 私は食べます, は hanya memberi topik: kalau soal saya, saya makan.",memory:"は = kalau soal…"},
  ga:{picture:"が seperti lampu sorot yang memilih siapa atau apa tepatnya yang dimaksud.",choose:"Pakai untuk menjawab siapa/apa, memperkenalkan keberadaan baru, serta dengan 好き・分かる・できる dan keadaan tubuh.",mistake:"Jangan mengganti semua subjek dengan は. 誰が来ましたか membutuhkan が karena yang dicari adalah siapa.",memory:"が = yang… / tepatnya…"},
  o:{picture:"を menempel pada benda yang dilewati oleh aksi: buku dibaca, air diminum, taman dilalui.",choose:"Cari kata kerja tindakan, lalu tanyakan ‘apa yang dikenai tindakan?’ Jawabannya biasanya memakai を.",mistake:"を dibaca o. Untuk tempat berlangsungnya kegiatan, gunakan で, bukan を.",memory:"を = sasaran aksi"},
  ni:{picture:"に adalah pin pada peta atau kalender: satu titik tujuan, waktu, penerima, atau keberadaan.",choose:"Pakai untuk tiba ke mana, berada di mana, pukul berapa, kepada siapa, atau berubah menjadi apa.",mistake:"Jangan pakai に untuk lokasi kegiatan aktif. 学校にいます, tetapi 学校で勉強します.",memory:"に = titik"},
  de:{picture:"で adalah panggung tempat aksi terjadi, atau alat yang membuat aksi dapat dilakukan.",choose:"Pakai untuk lokasi kegiatan, kendaraan/alat, bahasa, bahan, jumlah kelompok, dan kadang sebab.",mistake:"Ada tidak sama dengan melakukan. 猫が部屋にいます memakai に; 部屋で遊びます memakai で.",memory:"で = panggung / sarana"},
  e:{picture:"へ adalah panah yang mengarah ke suatu tempat; fokusnya arah perjalanan.",choose:"Pakai bersama kata kerja bergerak ketika ingin menekankan ‘menuju ke arah’.",mistake:"Sebagai partikel dibaca e, bukan he. Untuk waktu, penerima, dan keberadaan tetap gunakan に.",memory:"へ = panah arah"},
  to:{picture:"と mengikat hal secara tegas: A dan B, bersama seseorang, atau isi ucapan dalam tanda kutip.",choose:"Pakai untuk daftar lengkap, partner kegiatan, kutipan, dan hasil perbandingan/keputusan tertentu.",mistake:"Jika daftar hanya contoh dan masih ada item lain, gunakan や, bukan と.",memory:"と = ikatan lengkap"},
  mo:{picture:"も menambahkan anggota baru ke pernyataan yang sama: A juga begitu.",choose:"Gantikan は・が・を dengan も saat berarti juga; tempelkan setelah に・で・と bila partikelnya masih diperlukan.",mistake:"Jangan menulis をも untuk arti ‘juga’ pada pola dasar; biasanya を langsung diganti も.",memory:"も = juga / bahkan"},
  no:{picture:"の adalah rantai dua nomina: kata di kiri menjelaskan benda di kanan.",choose:"Pakai untuk pemilik, asal, jenis, isi, hubungan, atau menggantikan benda yang sudah jelas.",mistake:"Baca dari kanan: 日本語の本 adalah buku tentang/bahasa Jepang, bukan ‘Jepang milik buku’.",memory:"の = milik / tentang"},
  kara:{picture:"から adalah garis start: mulai dari tempat/waktu, atau alasan yang menjadi titik awal kesimpulan.",choose:"Pakai untuk ‘dari/sejak’ dan untuk alasan langsung ‘karena…’.",mistake:"Untuk alasan yang terasa lebih menjelaskan situasi, のです/ので sering lebih halus daripada から.",memory:"から = dari titik awal"},
  made:{picture:"まで adalah garis finis: kegiatan terus berlangsung sampai batas itu.",choose:"Pakai untuk batas akhir waktu atau tempat; sering berpasangan dengan から.",mistake:"まで bukan tenggat penyelesaian. ‘Selesai paling lambat Jumat’ memakai 金曜日までに.",memory:"まで = sampai batas"},
  ya:{picture:"や seperti membuka tas dan menunjukkan beberapa isi saja: A, B, dan lain-lain.",choose:"Pakai ketika item yang disebut hanya contoh dari daftar yang lebih panjang.",mistake:"Jangan gunakan や jika maksudnya hanya dan lengkap A serta B; gunakan と.",memory:"や = contoh daftar"},
  ka:{picture:"か mengubah kalimat menjadi pertanyaan atau menaruh dua kemungkinan sebagai pilihan.",choose:"Pakai di akhir pertanyaan sopan, di antara pilihan, dan dalam pertanyaan tak langsung seperti 何を食べるか.",mistake:"Dalam bentuk sopan cukup ですか; jangan menambahkan だ menjadi だですか.",memory:"か = ? / atau"},
  ne:{picture:"ね menoleh ke lawan bicara dan meminta rasa setuju: ‘ya, kan?’ ",choose:"Pakai saat informasi/perasaan dianggap dibagi bersama atau saat meminta konfirmasi lembut.",mistake:"Jangan pakai ね untuk berita yang lawan bicara jelas belum tahu; よ biasanya lebih cocok.",memory:"ね = kita sepakat, ya"},
  yo:{picture:"よ mendorong informasi ke lawan bicara: ‘saya beri tahu, lho’.",choose:"Pakai untuk informasi baru, koreksi lembut, peringatan, atau penegasan.",mistake:"Terlalu sering memakai よ dapat terdengar memaksa. よね menggabungkan pemberitahuan dan pencarian persetujuan.",memory:"よ = saya beri tahu"},
  dake:{picture:"だけ membuat pagar netral: yang masuk hanya bagian ini.",choose:"Pakai untuk membatasi nomina, jumlah, atau tindakan tanpa harus membuat predikat negatif.",mistake:"だけ tidak selalu berarti kekurangan. 一つだけ買いました hanya menyatakan membeli satu.",memory:"だけ = hanya, netral"},
  shika:{picture:"しか menutup semua pintu selain satu, lalu wajib ditemani bentuk negatif.",choose:"Pakai ketika ingin menekankan bahwa tidak ada pilihan/jumlah lain selain yang disebut.",mistake:"Predikat setelah しか harus negatif: 水しか飲みません, bukan 水しか飲みます.",memory:"しか〜ない = tidak selain"},
  "made-ni":{picture:"までに adalah alarm tenggat: aksi harus sudah terjadi sebelum atau tepat pada batas.",choose:"Pakai untuk tugas sekali selesai, kedatangan, pengumpulan, atau hasil yang harus tercapai pada tenggat.",mistake:"Bandingkan: 五時まで働く = terus bekerja sampai lima; 五時までに終わる = selesai paling lambat lima.",memory:"までに = paling lambat"},
};

export const PARTICLE_SOURCES = [
  {name:"Irodori · Japan Foundation",url:"https://www.irodori.jpf.go.jp/assets/data/Grammar_all.pdf",note:"Penjelasan fungsi partikel dalam situasi komunikasi A1–A2."},
  {name:"Tae Kim's Grammar Guide",url:"https://guidetojapanese.org/particles.html",note:"Model topik は, identifikasi が, serta latihan pembeda."},
  {name:"Tae Kim · Verb Particles",url:"https://guidetojapanese.org/particles2.html",note:"を・に・へ・で dan hubungan partikel dengan kata kerja."},
];
